name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi:
    name: PyPI
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/userhub-sdk

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install hatch
        run: pip install hatch==1.13.0

      - name: Build
        run: hatch build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
